name: Solid CI/CD
on: [push]
jobs:
  release:
    name: Run Automated Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install packages
      run: npm ci
    - name: Run ESlint
      run: npm run lint
    - name: Run Tests
      run: npm run test
