name: Node CI/CD
on: [push]
jobs:
  release:
    name: Run Automated Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install packages
      run: yarn install --frozen-lockfile
    - name: Run ESlint
      run: yarn lint
    - name: Run Tests
      run: yarn test
